"""Der Cookie-Assistent.

Die Pruefung ist hier der wertvolle Teil, nicht der Upload. Eine Cookie-Datei
scheitert auf drei Arten, die alle nach nichts aussehen - bis Stunden spaeter
der naechste Download rot wird. Genau diese drei Faelle sind unten
festgenagelt, und zwar gegen yt-dlps eigenen Lader: Was der nicht laden kann,
ist kaputt.
"""

from __future__ import annotations

from datetime import UTC, datetime, timedelta

import pytest

from app.services import cookies

KOPF = "# Netscape HTTP Cookie File\n# This file is generated by yt-dlp.  Do not edit.\n\n"

#: Ein Zeitpunkt weit in der Zukunft, damit die Tests nicht irgendwann von
#: selbst rot werden.
WEIT = int((datetime.now(UTC) + timedelta(days=90)).timestamp())


def zeile(name: str, wert: str = "x", ablauf: int | str = WEIT, domain: str = ".youtube.com") -> str:
    """Eine Zeile im Netscape-Format: 7 Felder, durch Tabulatoren getrennt."""
    return f"{domain}\tTRUE\t/\tTRUE\t{ablauf}\t{name}\t{wert}\n"


def datei(*namen: str, ablauf: int | str = WEIT) -> bytes:
    return (KOPF + "".join(zeile(n, ablauf=ablauf) for n in namen)).encode("utf-8")


#: Das Mindeste, was YouTube als Anmeldung durchgehen laesst - siehe
#: ``_has_auth_cookies`` im yt-dlp-Extractor.
GUELTIG = datei("LOGIN_INFO", "SAPISID", "HSID", "SSID")


@pytest.fixture(autouse=True)
def _ablage(tmp_path, monkeypatch):
    monkeypatch.setattr(cookies.settings, "data_dir", tmp_path)
    monkeypatch.setattr(cookies.settings, "ytdlp_cookies_file", None)
    return tmp_path


# ------------------------------------------------------------------ Pruefung


def test_angemeldete_datei_wird_angenommen(_ablage):
    befund = cookies.speichern(GUELTIG)
    assert befund.brauchbar
    assert befund.angemeldet
    assert "LOGIN_INFO" in befund.gefunden
    assert "SAPISID" in befund.gefunden
    assert befund.laeuft_ab is not None
    assert cookies.standardpfad().is_file()


def test_json_export_wird_erkannt(_ablage):
    """Der haeufigste Missgriff: Die Erweiterung exportiert JSON.

    yt-dlp wuerde nur "failed to load cookies" sagen - eine Meldung, aus der
    niemand ableiten kann, was zu tun ist.
    """
    befund = cookies.speichern(b'[{"domain": ".youtube.com", "name": "SID"}]')
    assert not befund.brauchbar
    assert "JSON" in befund.meldung
    assert "Netscape" in befund.meldung


def test_fehlende_kopfzeile_wird_erkannt(_ablage):
    """Ohne die Kopfzeile wirft Pythons MozillaCookieJar - und dann scheitert
    NICHT nur dieser Download, sondern jeder Aufruf an yt-dlp, auch das blosse
    Auflisten eines Kanals."""
    ohne_kopf = "".join(zeile(n) for n in ("LOGIN_INFO", "SAPISID")).encode("utf-8")
    befund = cookies.speichern(ohne_kopf)
    assert not befund.brauchbar
    assert "erste Zeile" in befund.meldung


def test_abgemeldet_exportierte_datei_wird_abgelehnt(_ablage):
    """Der heimtueckischste Fall: formal einwandfrei, aber ohne Anmeldung.

    Eine solche Datei wirkt exakt wie gar keine - man haelt das Problem fuer
    geloest und wundert sich, warum sich nichts aendert.
    """
    befund = cookies.speichern(datei("PREF", "VISITOR_INFO1_LIVE", "YSC"))
    assert not befund.brauchbar
    assert "keine Anmeldung" in befund.meldung
    assert "LOGIN_INFO" in befund.meldung


def test_login_info_allein_genuegt_nicht(_ablage):
    """yt-dlp verlangt LOGIN_INFO UND einen der SAPISID-Schluessel. Nur eines
    von beiden ist keine Anmeldung."""
    assert not cookies.speichern(datei("LOGIN_INFO")).brauchbar
    assert not cookies.speichern(datei("SAPISID")).brauchbar


def test_secure_3papisid_genuegt_als_ersatz(_ablage):
    """YouTube laesst SAPISID gelegentlich weg und liefert nur den
    3P-Schluessel - yt-dlp akzeptiert das, also muss der Assistent es auch."""
    befund = cookies.speichern(datei("LOGIN_INFO", "__Secure-3PAPISID"))
    assert befund.brauchbar, befund.meldung


def test_abgelaufene_anmeldung_wird_abgelehnt(_ablage):
    vergangen = int((datetime.now(UTC) - timedelta(days=1)).timestamp())
    befund = cookies.speichern(datei("LOGIN_INFO", "SAPISID", ablauf=vergangen))
    assert not befund.brauchbar
    assert "abgelaufen" in befund.meldung


def test_datei_ohne_youtube_cookies(_ablage):
    fremd = (KOPF + zeile("LOGIN_INFO", domain=".example.com")).encode("utf-8")
    befund = cookies.speichern(fremd)
    assert not befund.brauchbar
    assert "youtube.com" in befund.meldung


def test_leere_und_riesige_dateien(_ablage):
    assert "leer" in cookies.speichern(b"").meldung
    zu_gross = KOPF.encode() + b"#" * (cookies.MAX_BYTES + 1)
    assert not cookies.speichern(zu_gross).brauchbar


# ------------------------------------------------- Ersetzen nur bei Erfolg


def test_kaputter_upload_laesst_die_gute_datei_stehen(_ablage):
    """Der wichtigste Test des Moduls.

    Wer eine funktionierende Anmeldung hinterlegt hat und danach versehentlich
    die falsche Datei hochlaedt, darf nicht schlechter dastehen als vorher. Ein
    kaputtes cookiefile legt jeden yt-dlp-Aufruf lahm - das waere der
    schlechteste denkbare Ausgang eines Fehlgriffs.
    """
    assert cookies.speichern(GUELTIG).brauchbar
    vorher = cookies.standardpfad().read_bytes()

    assert not cookies.speichern(b'{"nicht": "netscape"}').brauchbar

    assert cookies.standardpfad().read_bytes() == vorher
    assert cookies.pruefen().brauchbar


def test_keine_reste_nach_abgelehntem_upload(_ablage):
    cookies.speichern(b'{"nicht": "netscape"}')
    cookies.speichern(datei("PREF"))
    uebrig = [p.name for p in _ablage.iterdir() if p.name.startswith(".cookies-")]
    assert uebrig == [], f"Zwischendateien liegengeblieben: {uebrig}"


# ------------------------------------------------------------ Welche gilt


def test_ohne_datei_ist_nichts_hinterlegt(_ablage):
    assert cookies.aktiver_pfad() is None
    befund = cookies.pruefen()
    assert not befund.brauchbar
    assert "Keine Cookie-Datei" in befund.meldung


def test_hochgeladene_datei_wird_benutzt(_ablage):
    cookies.speichern(GUELTIG)
    assert cookies.aktiver_pfad() == cookies.standardpfad()


def test_eigener_pfad_sticht_die_hochgeladene(_ablage, monkeypatch):
    """Wer seine Datei selbst ins Volume legt, soll das weiter tun koennen -
    sonst waere der Assistent eine Verschlechterung fuer bestehende Aufbauten."""
    cookies.speichern(GUELTIG)
    eigen = _ablage / "eigene.txt"
    eigen.write_bytes(GUELTIG)
    monkeypatch.setattr(cookies.settings, "ytdlp_cookies_file", eigen)
    assert cookies.aktiver_pfad() == eigen


def test_gesetzter_aber_fehlender_pfad_faellt_nicht_auf_die_hochgeladene_zurueck(
    _ablage, monkeypatch
):
    """Bewusst kein Rueckfall: Wer einen Pfad ausdruecklich setzt, meint ihn.
    Still eine andere Datei zu nehmen waere die schlimmere Ueberraschung."""
    cookies.speichern(GUELTIG)
    monkeypatch.setattr(cookies.settings, "ytdlp_cookies_file", _ablage / "gibtsnicht.txt")
    assert cookies.aktiver_pfad() is None


def test_entfernen(_ablage):
    cookies.speichern(GUELTIG)
    assert cookies.entfernen() is True
    assert cookies.aktiver_pfad() is None
    assert cookies.entfernen() is False


# --------------------------------------------------------- Wirkung auf yt-dlp


def test_hochgeladene_datei_landet_in_den_ytdlp_optionen(_ablage):
    from app.services import ytdlp

    assert "cookiefile" not in ytdlp._base_opts()
    cookies.speichern(GUELTIG)
    assert ytdlp._base_opts()["cookiefile"] == str(cookies.standardpfad())


def test_warnfrist(_ablage):
    bald = int((datetime.now(UTC) + timedelta(days=2)).timestamp())
    cookies.speichern(datei("LOGIN_INFO", "SAPISID", ablauf=bald))
    assert cookies.pruefen().als_dict()["bald_abgelaufen"] is True

    cookies.speichern(GUELTIG)  # 90 Tage
    assert cookies.pruefen().als_dict()["bald_abgelaufen"] is False


# ------------------------------------------------------------------- Endpunkte


@pytest.fixture
def client(_ablage, monkeypatch):
    from fastapi import FastAPI
    from fastapi.testclient import TestClient

    from app.api import cookies as api
    from app.db import get_db
    from app.services import drosselung
    from tests.conftest import neue_sitzung

    drosselung.zuruecksetzen()
    db = neue_sitzung()
    app = FastAPI()
    app.include_router(api.router)
    app.dependency_overrides[get_db] = lambda: db
    yield TestClient(app), db
    drosselung.zuruecksetzen()


def test_upload_ueber_die_oberflaeche(client):
    c, _ = client
    assert c.get("/api/cookies").json()["vorhanden"] is False

    antwort = c.post("/api/cookies", files={"datei": ("cookies.txt", GUELTIG, "text/plain")})
    assert antwort.status_code == 200
    daten = antwort.json()
    assert daten["brauchbar"] is True
    assert daten["angemeldet"] is True
    assert daten["vorhanden"] is True

    assert c.get("/api/cookies").json()["angemeldet"] is True


def test_upload_einer_untauglichen_datei_wird_abgelehnt(client):
    c, _ = client
    antwort = c.post(
        "/api/cookies", files={"datei": ("cookies.json", b'[{"a": 1}]', "application/json")}
    )
    assert antwort.status_code == 422
    # Die Begruendung muss durchgereicht werden - eine nackte 422 hilft niemandem.
    assert "JSON" in antwort.json()["detail"]


def test_loeschen(client):
    c, _ = client
    c.post("/api/cookies", files={"datei": ("cookies.txt", GUELTIG, "text/plain")})
    assert c.delete("/api/cookies").status_code == 200
    assert c.get("/api/cookies").json()["vorhanden"] is False
    assert c.delete("/api/cookies").status_code == 404


def test_probelauf_meldet_erfolg(client, monkeypatch):
    from app.services import ytdlp

    c, _ = client
    monkeypatch.setattr(
        ytdlp, "fetch_video_info",
        lambda vid: {"title": "Ein Video", "formats": [{"vcodec": "vp9", "width": 1920, "height": 1080}]},
    )
    daten = c.post("/api/cookies/test").json()
    assert daten["erfolg"] is True
    assert daten["angebotene_guete"] == 1080
    assert "1080p" in daten["meldung"]


def test_probelauf_meldet_fortbestehende_abweisung(client, monkeypatch):
    """Die aussagekraeftigste Antwort: Cookies hinterlegt und trotzdem
    abgewiesen - dann sind sie rotiert oder abgemeldet exportiert."""
    from app.services import drosselung, ytdlp

    c, _ = client

    def abgewiesen(_vid):
        raise ytdlp.Gedrosselt("Sign in to confirm you're not a bot")

    monkeypatch.setattr(ytdlp, "fetch_video_info", abgewiesen)
    daten = c.post("/api/cookies/test").json()
    assert daten["erfolg"] is False
    assert "rotiert" in daten["meldung"]
    # Und der Fehlversuch zaehlt wie jeder andere: Die Pause greift.
    assert drosselung.wartezeit() > 0


def test_probelauf_feuert_nicht_in_eine_laufende_pause(client, monkeypatch):
    """Sonst waere das Ergebnis unabhaengig von den Cookies ein Fehlschlag -
    und die Anfrage verlaengerte die Sperre, die man gerade abwartet."""
    from app.services import drosselung, ytdlp

    c, _ = client
    gerufen = []
    monkeypatch.setattr(ytdlp, "fetch_video_info", lambda vid: gerufen.append(vid))

    drosselung.melden("nicht als Bot bestaetigt")
    daten = c.post("/api/cookies/test").json()

    assert daten["pausiert"] is True
    assert daten["erfolg"] is False
    assert gerufen == [], "waehrend der Pause darf keine Anfrage rausgehen"


def test_probelauf_nimmt_ein_video_aus_der_eigenen_warteschlange(client, monkeypatch):
    """Ein Test an einem fremden Video sagt wenig. Interessant ist, ob genau
    die Videos durchkommen, die gerade nicht durchkommen."""
    from app.models import Channel, Video, VideoStatus
    from app.services import ytdlp

    c, db = client
    db.add(Channel(id="UCtest", name="Testkanal"))
    db.add(Video(id="meinvideo", channel_id="UCtest", title="X", status=VideoStatus.FAILED))
    db.commit()

    monkeypatch.setattr(ytdlp, "fetch_video_info", lambda vid: {"title": vid, "formats": []})
    assert c.post("/api/cookies/test").json()["video_id"] == "meinvideo"
